import { HercaInvestigation } from './types';

export const INITIAL_HERCA_INVESTIGATIONS: HercaInvestigation[] = [
  {
    id: 'inv-001',
    code: 'INV-2026-001',
    title: 'Troca Inadvertida de Válvula de CIP em Biorreator B14',
    incidentDate: '2026-03-10',
    shift: '2º Turno (14h - 22h)',
    sector: 'Fermentação & Biorreatores',
    station: 'Skid CIP Linha 03',
    operatorName: 'Carlos Eduardo Menezes',
    operatorExperienceMonths: 4,
    severity: 'critical',
    impactCategory: 'biological_contamination',
    estimatedLossReais: 48500,
    incidentDescription: 'Durante o ciclo de sanitização (CIP) do Biorreator B14, a válvula manual V-104 (retorno) foi aberta no lugar da válvula V-102 (dreno), provocando refluxo de solução cáustica a 80°C na linha estéril de inoculação e perda total do lote de 2.000 L de biomassa ativa.',
    immediateContainment: 'Interrupção emergencial da bomba dosadora CIP, isolamento da tubulação do B14, neutralização ácida com ácido fosfórico e descarte seguro em efluente industrial.',
    status: 'effective_validated',
    leadInvestigator: 'Engª Helena Vasconcellos (WCM Champion)',
    twttp: {
      knewWhat: true,
      knewWhatDetails: 'Operador conhecia a obrigação de alinhamento das linhas antes de disparar o ciclo CIP.',
      knewHow: false,
      knewHowDetails: 'Treinamento anterior foi apenas teórico em sala de aula. Não houve prática supervisionada no skid com teste das válvulas espelhadas.',
      knewWhy: false,
      knewWhyDetails: 'Não tinha clareza de que o retorno da soda pressurizada superaria o selo hidrostático da linha de inóculo.',
      hadConditions: false,
      hadConditionsDetails: 'Válvulas idênticas fisicamente, espaçadas por apenas 15cm e com identificação desgastada por vapores químicos.',
      leaderInstructionMethod: 2,
      leaderNotes: 'O supervisor apenas disse o que fazer, sem demonstrar no Gemba nem solicitar que o operador executasse sob observação crítica.'
    },
    hercaErrorType: 'slip',
    hercaSystemicFactors: [
      'Ergonomia desfavorável de manoplas idênticas adjacentes',
      'Ausência de dispositivo mecânico de intertravamento (Poka-Yoke)',
      'Iluminação insuficiente no nicho posterior do Skid (< 150 lux)'
    ],
    fiveWhys: {
      why1: 'Por que o Biorreator B14 foi contaminado com soda? Porque a válvula V-104 foi aberta equivocadamente durante o CIP.',
      why2: 'Por que o operador abriu a V-104 em vez da V-102? Porque ambas possuem o mesmo formato, cor e ficam lado a lado a 15 cm.',
      why3: 'Por que o operador não distinguiu os tags das válvulas? Porque a plaqueta de acrílico estava opaca e ilegível após lavagens cáusticas sucessivas.',
      why4: 'Por que o skid permitia abertura manual sem validação de fluxo? Porque o projeto de engenharia não adotou conceito de engenharia à prova de erro humano (Poka-Yoke).',
      why5: 'Por que o procedimento dependia 100% da atenção do operador? Ausência de avaliação sistêmica de falha humana (HERCA) na homologação dos novos skids.',
      rootCauseCategory: 'GestaoEngenharia',
      rootCauseStatement: 'Skid industrial concebido sem travas mecânicas Poka-Yoke com válvulas simétricas confusas, aliado a treinamento deficiente sem método de 4 passos TWTTP.'
    },
    actions: [
      {
        id: 'act-001',
        investigationId: 'inv-001',
        title: 'Trava mecânica de chave presa (Castell Key Poka-Yoke)',
        what: 'Instalar sistema mecânico com chave prisioneira que impede abrir a válvula de CIP se o dreno não estiver acoplado.',
        why: 'Eliminar 100% a possibilidade física de abertura indevida por engano humano.',
        who: 'Eng. Roberto Silveira (Manutenção)',
        where: 'Skid CIP 03 - Válvulas V-102/104',
        whenDate: '2026-03-16',
        how: 'Usinagem do suporte e travamento físico das hastes com chave sequencial.',
        howMuchCost: 3200,
        hierarchy: 'poka_yoke',
        status: 'verified_effective',
        completedDate: '2026-03-15',
        effectiveVerificationDate: '2026-03-20',
        isEffective: true
      },
      {
        id: 'act-002',
        investigationId: 'inv-001',
        title: 'Identificação visual fotoluminescente e codificação de cor',
        what: 'Pintar as manoplas em verde e amarelo de alta visibilidade e aplicar etiquetas em relevo metálico com gravação laser.',
        why: 'Facilitar diferenciação visual imediata mesmo em condições de baixa luminosidade.',
        who: 'Lucas Medeiros (Líder Turno)',
        where: 'Todos os 6 Skids de CIP da planta',
        whenDate: '2026-03-18',
        how: 'Pintura eletrostática das alavancas e rebitagem de plaquetas de aço inox 316L.',
        howMuchCost: 850,
        hierarchy: 'visual_control',
        status: 'verified_effective',
        completedDate: '2026-03-17',
        effectiveVerificationDate: '2026-03-20',
        isEffective: true
      },
      {
        id: 'act-003',
        investigationId: 'inv-001',
        title: 'Elaboração e fixação de Lição de Ponto Único OPL-2026-004',
        what: 'Criar OPL ilustrada passo a passo demonstrando o risco de contaminação e a sequência correta de sanitização.',
        why: 'Padronizar o entendimento operacional de forma rápida e visual no posto de trabalho.',
        who: 'Helena Vasconcellos (WCM)',
        where: 'Painel visual do Skid CIP 03',
        whenDate: '2026-03-15',
        how: 'Foto comparativa do Certo vs Errado com pontos de verificação e alertas de segurança.',
        howMuchCost: 150,
        hierarchy: 'procedure_opl',
        status: 'verified_effective',
        completedDate: '2026-03-15',
        effectiveVerificationDate: '2026-03-20',
        isEffective: true
      },
      {
        id: 'act-004',
        investigationId: 'inv-001',
        title: 'Ciclo TWTTP de 4 etapas para operadores de Biorreatores',
        what: 'Re-treinar todos os 18 operadores utilizando o método TWTTP com prova prática no Gemba e validação pelo líder.',
        why: 'Garantir que 100% da equipe compreende o que fazer, como fazer e por que fazer.',
        who: 'Helena Vasconcellos + Supervisores',
        where: 'Área de Fermentação',
        whenDate: '2026-03-22',
        how: 'Instrução em campo: 1. Explica, 2. Mostra, 3. Faz o operador fazer explicando os motivos, 4. Acompanha auditoria semanal.',
        howMuchCost: 0,
        hierarchy: 'training_twttp',
        status: 'verified_effective',
        completedDate: '2026-03-21',
        effectiveVerificationDate: '2026-03-21',
        isEffective: true
      }
    ],
    opl: {
      id: 'opl-001',
      investigationId: 'inv-001',
      code: 'OPL-2026-004',
      title: 'Sequenciamento Seguro e Poka-Yoke das Válvulas de CIP Linha 03',
      area: 'Fermentação & Biorreatores',
      station: 'Skid CIP Linha 03',
      classification: 'trouble_case',
      problemScenario: 'Válvula V-104 (retorno soda) acionada erroneamente no lugar de V-102 (dreno), causando refluxo e perda de batelada de biomassa.',
      standardPractice: '1. Inspecione visualmente o tag verde V-102. 2. Encaixe a chave prisioneira Castell Key. 3. Gire 90° até liberação do microswitch elétrico. 4. Confirme status de circuito fechado no painel da IHM.',
      keySafetyQualityPoint: 'JAMAIS forçar a manopla se a chave estiver travada. Trava mecânica indica linha não despressurizada.',
      whyItMatters: 'Protege a esterilidade da cultura celular (impacto de R$ 50k por batelada) e elimina risco de projeção de soda cáustica quente.',
      preparedBy: 'Helena Vasconcellos (WCM Specialist)',
      approvedBy: 'Dr. Marcos Toledo (Gerente de Planta)',
      createdAt: '2026-03-15'
    },
    recurrenceCount: 0,
    createdAt: '2026-03-10T14:30:00Z',
    updatedAt: '2026-03-21T18:00:00Z'
  },
  {
    id: 'inv-002',
    code: 'INV-2026-002',
    title: 'Inversão de Matriz de Estamparia na Prensa Hidráulica 400T',
    incidentDate: '2026-03-14',
    shift: '1º Turno (06h - 14h)',
    sector: 'Estamparia & Usinagem',
    station: 'Prensa Hidráulica PH-400',
    operatorName: 'Marcos Vinícius Batista',
    operatorExperienceMonths: 18,
    severity: 'high',
    impactCategory: 'production_stop',
    estimatedLossReais: 14200,
    incidentDescription: 'Durante setup de troca de ferramenta para estampar a peça ST-88, a matriz superior foi fixada invertida em 180°. Ao acionar o primeiro golpe em modo manual, ocorreu colisão violenta com cisalhamento das buchas guia e parada da linha por 4 horas e 30 minutos.',
    immediateContainment: 'Acionamento do botão cogumelo de emergência, bloqueio elétrico/mecânico da prensa (LOTO) e remoção da ferramenta avariada para diagnóstico na ferramentaria.',
    status: 'actions_pending',
    leadInvestigator: 'Carlos Drumond (Engenharia de Processos)',
    twttp: {
      knewWhat: true,
      knewWhatDetails: 'Operador experiente, sabia montar e centrar o conjunto de matrizes.',
      knewHow: true,
      knewHowDetails: 'Dominava o manuseio da ponte rolante e o aperto do torpedo hidráulico.',
      knewWhy: true,
      knewWhyDetails: 'Sabia do risco de choque entre os componentes móveis e fixos.',
      hadConditions: false,
      hadConditionsDetails: 'A matriz antiga não possui pinos assimétricos de posicionamento (foolproof), permitindo montagem mecânica perfeitamente invertida sem resistência física.',
      leaderInstructionMethod: 3,
      leaderNotes: 'O método de ensino foi bom, porém o líder confiou apenas na rotina e memória do colaborador sem haver barreira física.'
    },
    hercaErrorType: 'mistake_rule',
    hercaSystemicFactors: [
      'Ferramenta sem assimetria geométrica de posicionamento (Poka-Yoke)',
      'Pressão por tempo de setup rápido gerando foco seletivo em aperto de parafusos em vez de orientação',
      'Checklist de setup genérico sem ponto de checagem obrigatório de posição do rasgo chaveta'
    ],
    fiveWhys: {
      why1: 'Por que o punção quebrou? Porque a matriz superior desceu desalinhada em 180° com a matriz inferior.',
      why2: 'Por que foi montada desalinhada? Porque o operador posicionou a placa virada para trás.',
      why3: 'Por que a máquina permitiu a fixação na posição errada? Porque as furações de fixação da mesa são totalmente simétricas.',
      why4: 'Por que a matriz não possui pino de guia assimétrico? Porque a ferramentaria desenhou a matriz sem norma de Poka-Yoke mecânico.',
      why5: 'Por que os padrões de engenharia de ferramentas não exigem assimetria obrigatória? Falha na diretriz de DFM (Design for Manufacturing) do pilar Early Equipment Management do WCM.',
      rootCauseCategory: 'Maquina',
      rootCauseStatement: 'Molde concebido com fixação simétrica permitindo montagem incorreta, sem pino guia diferenciado (ausência de Poka-Yoke de projeto).'
    },
    actions: [
      {
        id: 'act-005',
        investigationId: 'inv-002',
        title: 'Usinagem de pino de guia assimétrico Poka-Yoke',
        what: 'Fresar rasgo de chaveta excêntrico e instalar pino guia em diâmetro diferenciado (35mm vs 28mm) que impede fisicamente o encaixe em 180°.',
        why: 'Tornar fisicamente impossível fixar a matriz invertida.',
        who: 'Mestre Tiago (Ferramentaria)',
        where: 'Matriz ST-88 e mesa da Prensa PH-400',
        whenDate: '2026-03-24',
        how: 'Eletroerosão a fio e montagem de pino temperado na base superior.',
        howMuchCost: 1900,
        hierarchy: 'poka_yoke',
        status: 'in_progress'
      },
      {
        id: 'act-006',
        investigationId: 'inv-002',
        title: 'Sensor óptico de presença e orientação de molde',
        what: 'Instalar barreira óptica de feixe reflexivo conectado ao CLP que bloqueia o comando bimanual se a matriz estiver invertida.',
        why: 'Garantir segunda barreira automática de segurança de processo.',
        who: 'Eng. Douglas (Automação)',
        where: 'Prensa PH-400',
        whenDate: '2026-03-26',
        how: 'Instalação de sensor Omron e intertravamento na safety-PLC.',
        howMuchCost: 2800,
        hierarchy: 'engineering',
        status: 'pending'
      },
      {
        id: 'act-007',
        investigationId: 'inv-002',
        title: 'Criação de OPL com seta direcional e checagem visual',
        what: 'Fixar OPL na prensa e adesivar setas de casamento visual amarelo/preto que devem coincidir no setup.',
        why: 'Evidenciar o alinhamento correto em menos de 2 segundos.',
        who: 'Carlos Drumond',
        where: 'Prensa PH-400',
        whenDate: '2026-03-20',
        how: 'Pintura poliuretano de alto contraste e OPL laminada.',
        howMuchCost: 120,
        hierarchy: 'visual_control',
        status: 'completed',
        completedDate: '2026-03-19'
      }
    ],
    recurrenceCount: 1,
    createdAt: '2026-03-14T09:15:00Z',
    updatedAt: '2026-03-19T16:20:00Z'
  },
  {
    id: 'inv-003',
    code: 'INV-2026-003',
    title: 'Dosagem Incorreta de Antiespumante no Biorreator Piloto B07',
    incidentDate: '2026-03-18',
    shift: '3º Turno (22h - 06h)',
    sector: 'Fermentação & Biorreatores',
    station: 'Biorreator Piloto B07',
    operatorName: 'Patrícia Lima Duarte',
    operatorExperienceMonths: 2,
    severity: 'medium',
    impactCategory: 'quality',
    estimatedLossReais: 6800,
    incidentDescription: 'Operadora recém-admitida conectou frasco de antiespumante concentrado a 100% no lugar da solução pré-diluída a 10%, ocasionando queda brusca na taxa de transferência de oxigênio dissolvido (kLa) da fermentação de levedura recombinante.',
    immediateContainment: 'Interrupção imediata da bomba peristáltica, aumento da velocidade do agitador tipo Rushton para 650 RPM e injeção de oxigênio puro suplementar.',
    status: 'under_investigation',
    leadInvestigator: 'Felipe Guimarães (Coordenação de Qualidade)',
    twttp: {
      knewWhat: true,
      knewWhatDetails: 'Sabia que deveria repor o reservatório de antiespumante ao soar o alarme na IHM.',
      knewHow: false,
      knewHowDetails: 'Não sabia diferenciar os recipientes plásticos brancos que possuem a mesma tampa e volumetria.',
      knewWhy: false,
      knewWhyDetails: 'Não tinha conhecimento da inibição respiratória celular causada por excesso de silicone nas microbolhas.',
      hadConditions: false,
      hadConditionsDetails: 'Frascos armazenados na mesma prateleira sem código de cores e com bocais padrão que encaixam no mesmo tubo de silicone.',
      leaderInstructionMethod: 1,
      leaderNotes: 'O instrutor apenas entregou o procedimento operacional padrão (POP) em papel para a operadora ler sozinha no primeiro dia de trabalho.'
    },
    hercaErrorType: 'lapse',
    hercaSystemicFactors: [
      'Frascos de produtos com dosagens diferentes armazenados no mesmo nicho',
      'Conexões universais luer-lock sem distinção física de bitola',
      'TWTTP Nível 1 (apenas leitura passiva sem acompanhamento prático)'
    ],
    fiveWhys: {
      why1: 'Por que o oxigênio dissolvido caiu a zero? Porque o meio de cultura foi sobrecarregado com antiespumante concentrado.',
      why2: 'Por que foi injetada a solução concentrada? Porque a operadora pegou o frasco de estoque bruto em vez do frasco de trabalho diluído.',
      why3: 'Por que ela pegou o frasco errado? Porque ambos são galões brancos de polietileno com o mesmo rótulo padrão de almoxarifado.',
      why4: 'Por que os frascos não possuem bocal ou conector diferenciado? Porque o laboratório utiliza mangueiras universais sem Poka-Yoke.',
      why5: 'Por que a operadora novata não pediu confirmação? Porque o líder não realizou o método TWTTP de 4 passos com certificação de habilidade.',
      rootCauseCategory: 'Metodo',
      rootCauseStatement: 'Falta de sistema Poka-Yoke de encaixe para soluções químicas e método inadequado de treinamento (Nível 1 TWTTP).'
    },
    actions: [
      {
        id: 'act-008',
        investigationId: 'inv-003',
        title: 'Conectores rápidos incompatíveis (Poka-Yoke de conexão)',
        what: 'Substituir os engates rápidos dos frascos por tipos macho/fêmea incompatíveis entre concentrado e diluído.',
        why: 'Impossibilitar fisicamente a conexão da mangueira errada na bomba peristáltica.',
        who: 'Eng. Vanessa Cruz',
        where: 'Bancada de alimentação de Biorreatores Piloto',
        whenDate: '2026-03-25',
        how: 'Instalação de engates CPC de cores e diâmetros distintos (Azul 6mm / Vermelho 10mm).',
        howMuchCost: 650,
        hierarchy: 'poka_yoke',
        status: 'in_progress'
      },
      {
        id: 'act-009',
        investigationId: 'inv-003',
        title: 'Treinamento completo TWTTP com avaliação prática',
        what: 'Executar treinamento de 4 etapas para operadores de biorreatores piloto com foco em impacto biológico e manuseio de insumos.',
        why: 'Garantir que o operador saiba o Que, o Como e o Por que.',
        who: 'Felipe Guimarães',
        where: 'Laboratório Piloto',
        whenDate: '2026-03-27',
        how: 'Ciclo TWTTP com o líder demonstrando no Gemba e validando execução autônoma.',
        howMuchCost: 0,
        hierarchy: 'training_twttp',
        status: 'pending'
      }
    ],
    recurrenceCount: 0,
    createdAt: '2026-03-18T03:40:00Z',
    updatedAt: '2026-03-18T10:00:00Z'
  }
];
